# Generated by Django 2.2.4 on 2022-06-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_auto_20220623_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_wished_by',
            new_name='user_who_wish',
        ),
    ]
